services:
  - type: web
    name: hedera-backend
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
